In [3]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ajitn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\ajitn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ajitn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ajitn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\ajitn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
data = {'Name': ['Alice','Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

In [8]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name','Age'])

In [9]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [10]:
df.tail()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [12]:
df['Name']
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [13]:
df.loc[0]
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [14]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [16]:
df['Gender'] = ['F','M']
df.drop('Age',axis = 1, inplace=True)

In [17]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [18]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [19]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M